// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUGE_OC7m1VYSsMLT4rbFNcv8I9bl99Yc',
    appId: '1:398566262302:web:2dc24db93f7b0589b9100f',
    messagingSenderId: '398566262302',
    projectId: 'hackoverflow-55790',
    authDomain: 'hackoverflow-55790.firebaseapp.com',
    storageBucket: 'hackoverflow-55790.appspot.com',
    measurementId: 'G-C9DL2F2CCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9dqiPJ9sOz8_-Wig6PKjH0FnKpS1qaks',
    appId: '1:398566262302:android:ebcc2c0c3e61b832b9100f',
    messagingSenderId: '398566262302',
    projectId: 'hackoverflow-55790',
    storageBucket: 'hackoverflow-55790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGfC1-kEiLWtGD7dzn3IHme0iJNr57TWk',
    appId: '1:398566262302:ios:1c0cb1a0ec193ca2b9100f',
    messagingSenderId: '398566262302',
    projectId: 'hackoverflow-55790',
    storageBucket: 'hackoverflow-55790.appspot.com',
    iosBundleId: 'com.example.hackoverflowMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGfC1-kEiLWtGD7dzn3IHme0iJNr57TWk',
    appId: '1:398566262302:ios:7a4259dafc2a536db9100f',
    messagingSenderId: '398566262302',
    projectId: 'hackoverflow-55790',
    storageBucket: 'hackoverflow-55790.appspot.com',
    iosBundleId: 'com.example.hackoverflowMobile.RunnerTests',
  );
}
